import { PetProduct } from "./types";

// Mock pet product data inspired by Pet Circle with products for 12+ pet types
export const petProducts: PetProduct[] = [
  // ========== DOG PRODUCTS ==========
  {
    id: "1",
    name: "Royal Canin Adult Dry Dog Food",
    description: "Complete nutrition for adult dogs. Rich in protein and essential vitamins.",
    price: 89.99,
    originalPrice: 109.99,
    image: "https://images.unsplash.com/photo-1589924691995-8dc6c2028da5?w=400&h=400&fit=crop",
    category: "food",
    petType: "dog",
    rating: 4.8,
    reviewCount: 1247,
    brand: "Royal Canin",
    inStock: true,
    badges: ["Best Seller", "Auto-Delivery"],
  },
  {
    id: "2",
    name: "Premium Puppy Wet Food Pack",
    description: "High-quality wet food for growing puppies. 12 cans variety pack.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "food",
    petType: "dog",
    rating: 4.9,
    reviewCount: 543,
    brand: "Premium Pets",
    inStock: true,
    badges: ["New", "Best Seller"],
  },
  {
    id: "3",
    name: "Rope Tug Toy - Large",
    description: "Heavy-duty rope toy for interactive play. Perfect for fetch and tug-of-war.",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop",
    category: "toys",
    petType: "dog",
    rating: 4.5,
    reviewCount: 678,
    brand: "Tough Toys",
    inStock: true,
    badges: [],
  },
  {
    id: "4",
    name: "Interactive Puzzle Feeder",
    description: "Mental stimulation toy that makes mealtime fun. Durable and easy to clean.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=400&fit=crop",
    category: "toys",
    petType: "dog",
    rating: 4.6,
    reviewCount: 312,
    brand: "PlaySmart",
    inStock: true,
    badges: ["Popular"],
  },
  {
    id: "5",
    name: "Flea & Tick Treatment - 3 Month Supply",
    description: "Veterinary recommended protection. Kills fleas, ticks, and lice.",
    price: 49.99,
    originalPrice: 59.99,
    image: "https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400&h=400&fit=crop",
    category: "health",
    petType: "dog",
    rating: 4.7,
    reviewCount: 1123,
    brand: "VetGuard",
    inStock: true,
    badges: ["Auto-Delivery", "Best Seller"],
  },
  {
    id: "6",
    name: "Comfort Dog Bed - Large",
    description: "Orthopedic memory foam bed. Water-resistant cover, machine washable.",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "dog",
    rating: 4.8,
    reviewCount: 934,
    brand: "Comfy Pets",
    inStock: true,
    badges: ["Best Seller"],
  },
  {
    id: "7",
    name: "Training Treats - Chicken Flavor",
    description: "Small, soft training treats. Perfect for positive reinforcement training.",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "treats",
    petType: "dog",
    rating: 4.9,
    reviewCount: 1123,
    brand: "TrainRight",
    inStock: true,
    badges: ["Best Seller"],
  },

  // ========== CAT PRODUCTS ==========
  {
    id: "8",
    name: "Hill's Science Diet Adult Cat Food",
    description: "Balanced nutrition for indoor cats. Supports healthy weight management.",
    price: 64.99,
    originalPrice: 79.99,
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop",
    category: "food",
    petType: "cat",
    rating: 4.7,
    reviewCount: 892,
    brand: "Hill's",
    inStock: true,
    badges: ["Auto-Delivery"],
  },
  {
    id: "9",
    name: "Grain-Free Cat Food - Salmon",
    description: "Premium grain-free formula with real salmon. Natural ingredients only.",
    price: 54.99,
    image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=400&fit=crop",
    category: "food",
    petType: "cat",
    rating: 4.7,
    reviewCount: 445,
    brand: "Natural Pet",
    inStock: true,
    badges: ["Auto-Delivery"],
  },
  {
    id: "10",
    name: "Catnip Feather Wand",
    description: "Interactive wand toy with natural catnip. Keeps your cat active and entertained.",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=400&h=400&fit=crop",
    category: "toys",
    petType: "cat",
    rating: 4.8,
    reviewCount: 445,
    brand: "Cat Zone",
    inStock: true,
    badges: ["Best Seller"],
  },
  {
    id: "11",
    name: "Cat Scratching Post Tower",
    description: "Multi-level cat tree with scratching posts. Includes hideaway and perches.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "cat",
    rating: 4.6,
    reviewCount: 623,
    brand: "Cat Haven",
    inStock: true,
    badges: [],
  },
  {
    id: "12",
    name: "Freeze-Dried Salmon Treats for Cats",
    description: "100% natural freeze-dried salmon. Single ingredient, high protein.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=400&fit=crop",
    category: "treats",
    petType: "cat",
    rating: 4.8,
    reviewCount: 789,
    brand: "Natural Choice",
    inStock: true,
    badges: ["Popular"],
  },

  // ========== BIRD PRODUCTS ==========
  {
    id: "13",
    name: "Premium Parrot Seed Mix",
    description: "Nutritious blend for parrots and large birds. Vitamins and minerals included.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop",
    category: "food",
    petType: "bird",
    rating: 4.6,
    reviewCount: 234,
    brand: "Avian Nutrition",
    inStock: true,
    badges: [],
  },
  {
    id: "14",
    name: "Canary & Finch Food Blend",
    description: "Specially formulated for small birds. High-quality seeds and grains.",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "food",
    petType: "bird",
    rating: 4.5,
    reviewCount: 178,
    brand: "Bird Feed Co",
    inStock: true,
    badges: [],
  },
  {
    id: "15",
    name: "Bird Swing with Bell",
    description: "Colorful swing toy with bell attachment. Encourages play and exercise.",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=400&h=400&fit=crop",
    category: "toys",
    petType: "bird",
    rating: 4.7,
    reviewCount: 312,
    brand: "Playful Birds",
    inStock: true,
    badges: [],
  },
  {
    id: "16",
    name: "Large Bird Cage with Stand",
    description: "Spacious cage with multiple perches. Includes food dishes and toys.",
    price: 199.99,
    originalPrice: 249.99,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "bird",
    rating: 4.8,
    reviewCount: 456,
    brand: "Avian Home",
    inStock: true,
    badges: ["Best Seller"],
  },

  // ========== FISH PRODUCTS ==========
  {
    id: "17",
    name: "Premium Tropical Fish Flakes",
    description: "Nutritionally balanced flakes for tropical fish. Enhances color and vitality.",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop",
    category: "food",
    petType: "fish",
    rating: 4.6,
    reviewCount: 567,
    brand: "AquaFeed",
    inStock: true,
    badges: [],
  },
  {
    id: "18",
    name: "Goldfish Pellets - Large Container",
    description: "Slow-sinking pellets for goldfish. Promotes healthy digestion.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "food",
    petType: "fish",
    rating: 4.7,
    reviewCount: 423,
    brand: "Goldfish Pro",
    inStock: true,
    badges: [],
  },
  {
    id: "19",
    name: "10 Gallon Aquarium Starter Kit",
    description: "Complete aquarium setup with filter, heater, and LED lights.",
    price: 89.99,
    originalPrice: 119.99,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "fish",
    rating: 4.5,
    reviewCount: 789,
    brand: "AquaTank",
    inStock: true,
    badges: ["Popular"],
  },
  {
    id: "20",
    name: "Aquarium Water Conditioner",
    description: "Removes chlorine and chloramines. Safe for all fish types.",
    price: 11.99,
    image: "https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400&h=400&fit=crop",
    category: "health",
    petType: "fish",
    rating: 4.8,
    reviewCount: 1123,
    brand: "AquaCare",
    inStock: true,
    badges: ["Best Seller"],
  },

  // ========== REPTILE PRODUCTS ==========
  {
    id: "21",
    name: "Bearded Dragon Food Pellets",
    description: "Complete nutrition for bearded dragons. Rich in vitamins and calcium.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1589924691995-8dc6c2028da5?w=400&h=400&fit=crop",
    category: "food",
    petType: "reptile",
    rating: 4.5,
    reviewCount: 189,
    brand: "Reptile Nutrition",
    inStock: true,
    badges: [],
  },
  {
    id: "22",
    name: "Snake Frozen Mice - Pack of 10",
    description: "High-quality frozen feeder mice. Safe and convenient.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "food",
    petType: "reptile",
    rating: 4.6,
    reviewCount: 234,
    brand: "Reptile Feeders",
    inStock: true,
    badges: [],
  },
  {
    id: "23",
    name: "Reptile Heat Lamp with Bulb",
    description: "Ceramic heat emitter for terrariums. Safe and efficient heating.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "reptile",
    rating: 4.7,
    reviewCount: 456,
    brand: "Reptile Heat",
    inStock: true,
    badges: [],
  },
  {
    id: "24",
    name: "Reptile Calcium Powder",
    description: "Essential calcium supplement with D3. Prevents metabolic bone disease.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400&h=400&fit=crop",
    category: "health",
    petType: "reptile",
    rating: 4.8,
    reviewCount: 567,
    brand: "Reptile Care",
    inStock: true,
    badges: ["Best Seller"],
  },

  // ========== RABBIT PRODUCTS ==========
  {
    id: "25",
    name: "Premium Rabbit Pellets",
    description: "High-fiber pellets for adult rabbits. Supports digestive health.",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1589924691995-8dc6c2028da5?w=400&h=400&fit=crop",
    category: "food",
    petType: "rabbit",
    rating: 4.6,
    reviewCount: 312,
    brand: "Bunny Nutrition",
    inStock: true,
    badges: [],
  },
  {
    id: "26",
    name: "Timothy Hay - Large Bale",
    description: "Fresh timothy hay for rabbits. Promotes healthy teeth and digestion.",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "food",
    petType: "rabbit",
    rating: 4.9,
    reviewCount: 678,
    brand: "Hay Master",
    inStock: true,
    badges: ["Best Seller"],
  },
  {
    id: "27",
    name: "Rabbit Chew Toys Set",
    description: "Variety pack of safe chew toys. Helps maintain healthy teeth.",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=400&h=400&fit=crop",
    category: "toys",
    petType: "rabbit",
    rating: 4.5,
    reviewCount: 234,
    brand: "Bunny Toys",
    inStock: true,
    badges: [],
  },

  // ========== HAMSTER PRODUCTS ==========
  {
    id: "28",
    name: "Hamster Food Mix - Seed Blend",
    description: "Complete nutrition mix with seeds, grains, and vegetables.",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1589924691995-8dc6c2028da5?w=400&h=400&fit=crop",
    category: "food",
    petType: "hamster",
    rating: 4.7,
    reviewCount: 456,
    brand: "Hamster Feed",
    inStock: true,
    badges: [],
  },
  {
    id: "29",
    name: "Hamster Exercise Wheel",
    description: "Silent running wheel for hamsters. Safe and durable design.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "hamster",
    rating: 4.8,
    reviewCount: 789,
    brand: "Pet Exercise",
    inStock: true,
    badges: ["Best Seller"],
  },
  {
    id: "30",
    name: "Hamster Cage Accessories Set",
    description: "Includes hideout, water bottle, and food dish. Complete starter set.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "hamster",
    rating: 4.6,
    reviewCount: 523,
    brand: "Small Pet Pro",
    inStock: true,
    badges: [],
  },

  // ========== GUINEA PIG PRODUCTS ==========
  {
    id: "31",
    name: "Guinea Pig Pellets with Vitamin C",
    description: "Fortified pellets with added vitamin C. Essential for guinea pig health.",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "food",
    petType: "guinea-pig",
    rating: 4.7,
    reviewCount: 445,
    brand: "Cavy Nutrition",
    inStock: true,
    badges: [],
  },
  {
    id: "32",
    name: "Guinea Pig Hay Rack",
    description: "Stainless steel hay rack. Keeps hay clean and accessible.",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "guinea-pig",
    rating: 4.5,
    reviewCount: 234,
    brand: "Small Pet Accessories",
    inStock: true,
    badges: [],
  },

  // ========== FERRET PRODUCTS ==========
  {
    id: "33",
    name: "Ferret Food - High Protein",
    description: "Grain-free formula with high protein. Meets ferret nutritional needs.",
    price: 27.99,
    image: "https://images.unsplash.com/photo-1589924691995-8dc6c2028da5?w=400&h=400&fit=crop",
    category: "food",
    petType: "ferret",
    rating: 4.6,
    reviewCount: 178,
    brand: "Ferret Pro",
    inStock: true,
    badges: [],
  },
  {
    id: "34",
    name: "Ferret Tunnel Play Set",
    description: "Collapsible tunnel system. Hours of entertainment for active ferrets.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=400&h=400&fit=crop",
    category: "toys",
    petType: "ferret",
    rating: 4.8,
    reviewCount: 312,
    brand: "Ferret Play",
    inStock: true,
    badges: ["Popular"],
  },

  // ========== TURTLE PRODUCTS ==========
  {
    id: "35",
    name: "Aquatic Turtle Food Sticks",
    description: "Nutritionally complete floating sticks. Suitable for all aquatic turtles.",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "food",
    petType: "turtle",
    rating: 4.7,
    reviewCount: 267,
    brand: "Turtle Nutrition",
    inStock: true,
    badges: [],
  },
  {
    id: "36",
    name: "Turtle Basking Platform",
    description: "Floating basking platform with ramp. Helps turtles dry off and regulate temperature.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "turtle",
    rating: 4.6,
    reviewCount: 189,
    brand: "Aqua Platforms",
    inStock: true,
    badges: [],
  },

  // ========== HEDGEHOG PRODUCTS ==========
  {
    id: "37",
    name: "Hedgehog Food - Insectivore Diet",
    description: "High-quality insectivore formula. Meets hedgehog nutritional requirements.",
    price: 21.99,
    image: "https://images.unsplash.com/photo-1589924691995-8dc6c2028da5?w=400&h=400&fit=crop",
    category: "food",
    petType: "hedgehog",
    rating: 4.6,
    reviewCount: 156,
    brand: "Hedgehog Feed",
    inStock: true,
    badges: [],
  },
  {
    id: "38",
    name: "Hedgehog Exercise Wheel",
    description: "Large silent wheel for hedgehogs. Smooth running surface.",
    price: 22.99,
    image: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "hedgehog",
    rating: 4.8,
    reviewCount: 234,
    brand: "Small Pet Exercise",
    inStock: true,
    badges: [],
  },

  // ========== CHINCHILLA PRODUCTS ==========
  {
    id: "39",
    name: "Chinchilla Pellets",
    description: "Specialized pellets for chinchillas. High fiber, low fat formula.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1534361960057-19889db82411?w=400&h=400&fit=crop",
    category: "food",
    petType: "chinchilla",
    rating: 4.7,
    reviewCount: 198,
    brand: "Chinchilla Nutrition",
    inStock: true,
    badges: [],
  },
  {
    id: "40",
    name: "Chinchilla Dust Bath",
    description: "Volcanic dust for chinchilla grooming. Maintains healthy fur.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "chinchilla",
    rating: 4.9,
    reviewCount: 456,
    brand: "Chinchilla Care",
    inStock: true,
    badges: ["Best Seller"],
  },

  // ========== ADDITIONAL PRODUCTS ==========
  {
    id: "41",
    name: "Dental Chew Bones - Large Pack",
    description: "Long-lasting dental chews. Promotes healthy gums and clean teeth.",
    price: 17.99,
    originalPrice: 24.99,
    image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=400&fit=crop",
    category: "treats",
    petType: "dog",
    rating: 4.6,
    reviewCount: 567,
    brand: "ChewMaster",
    inStock: true,
    badges: [],
  },
  {
    id: "42",
    name: "Joint Support Supplement",
    description: "Glucosamine and chondroitin supplement for joint health. 120 tablets.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1596854302667-326e7fc0e9c7?w=400&h=400&fit=crop",
    category: "health",
    petType: "dog",
    rating: 4.6,
    reviewCount: 789,
    brand: "Wellness Plus",
    inStock: true,
    badges: ["Popular"],
  },
  {
    id: "43",
    name: "Leather Leash with Padded Handle",
    description: "Premium leather leash. Comfortable padded handle, multiple color options.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "dog",
    rating: 4.5,
    reviewCount: 456,
    brand: "Premium Leash",
    inStock: true,
    badges: [],
  },
  {
    id: "44",
    name: "Automatic Pet Feeder",
    description: "Smart feeder with timer. Portion control and scheduled feeding.",
    price: 149.99,
    originalPrice: 179.99,
    image: "https://images.unsplash.com/photo-1589924691995-8dc6c2028da5?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "dog",
    rating: 4.7,
    reviewCount: 623,
    brand: "SmartFeed",
    inStock: true,
    badges: ["New", "Auto-Delivery"],
  },
  {
    id: "45",
    name: "Dental Care Chew Sticks",
    description: "Natural dental chews that clean teeth and freshen breath. 30 pieces.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1596854302667-326e7fc0e9c7?w=400&h=400&fit=crop",
    category: "health",
    petType: "dog",
    rating: 4.4,
    reviewCount: 567,
    brand: "CleanTeeth",
    inStock: true,
    badges: [],
  },
  {
    id: "46",
    name: "Portable Pet Water Bottle",
    description: "Leak-proof water bottle with built-in bowl. Perfect for walks and travel.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=400&h=400&fit=crop",
    category: "accessories",
    petType: "dog",
    rating: 4.4,
    reviewCount: 278,
    brand: "TravelPaw",
    inStock: true,
    badges: [],
  },
];
